language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script:
  - tiddlywiki ./wiki --load wiki_explore_gardening.html
  - tiddlywiki ./wiki --build

after_success:
  - bash ./publish.sh

branches:
  only:
    - master
    - feature-generate-from-single-html-file

